"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$python\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold #4c4f69"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "#9D8ECE"
format = "[$symbol$branch]($style) "

[git_status]
style = "#d20f39"
format = '([$all_status$ahead_behind]($style) )'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "!${count}"
untracked = "?${count}"
staged = "+${count}"

[python]
symbol = " "
style = "#fe640b"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[cmd_duration]
min_time = 2_000
style = "#9ca0b0"
format = "[$duration]($style) "

[character]
success_symbol = "[❯](#9D8ECE)"
error_symbol = "[❯](#d20f39)"
