# Theme: dark (Catppuccin Macchiato + soft purple)
# Applied by theme-switch; sourced from hyprland.conf

env = XCURSOR_THEME,Bibata-Modern-Ice
env = GTK_THEME,adw-gtk3-dark

general {
    col.active_border = rgba(9D8ECEcc)
    col.inactive_border = rgba(5b6078ff)
}

decoration {
    dim_strength = 0.08
    blur {
        brightness = 0.8
    }
}
