"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$python\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold #cad3f5"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "#B2A4D4"
format = "[$symbol$branch]($style) "

[git_status]
style = "#ed8796"
format = '([$all_status$ahead_behind]($style) )'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "!${count}"
untracked = "?${count}"
staged = "+${count}"

[python]
symbol = " "
style = "#f5a97f"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[cmd_duration]
min_time = 2_000
style = "#6e738d"
format = "[$duration]($style) "

[character]
success_symbol = "[❯](#B2A4D4)"
error_symbol = "[❯](#ed8796)"
